# Generated by Django 4.1.3 on 2022-11-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaAtencion', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=100)),
                ('tratamiento', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('nombreDueño', models.CharField(max_length=50)),
                ('apellidoDueño', models.CharField(max_length=50)),
                ('emailfonoDueño', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
