# Generated by Django 4.1.3 on 2022-11-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascotas',
            old_name='emailfonoDueño',
            new_name='emailDueño',
        ),
    ]
